#! /usr/bin/env ruby
# frozen_string_literal: true

require 'pg'

def connect_to_db
  connection = PG.connect(dbname: 'expenses')
  connection.exec 'SELECT * FROM expenses;'
end

def list_expenses
  result = connect_to_db

  result.each do |tuple|
    columns = [tuple['id'],
               tuple['created_on'],
               tuple['amount'].rjust(7),
               tuple['memo']]

    puts columns.join(' | ')
  end
end

def display_help
  puts <<~HELP
    An expense recording system

    Commands:

    add AMOUNT MEMO [DATE] - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo 
    
  HELP
end

command = ARGV[0]
case command
when 'list' then list_expenses
else display_help
end
