#! /usr/bin/env ruby
# frozen_string_literal: true

require 'pg'

db = PG.connect(dbname: 'expenses')
result = db.exec 'SELECT * FROM expenses;'

result.each do |tuple|
  columns = [
    tuple['id'],
    tuple['created_on'],
    tuple['amount'].rjust(7),
    tuple['memo']
  ]

  puts columns.join(' | ')
end
